#!/usr/bin/env python2

 # ffmpeg -i $name.mp4 -c:v mjpeg -q:v 3 -an $name.mpg;
  #ffmpeg -i $name.m -acodec pcm_s16le -ac 2 $name.wav;

import sys, os

def printHelp():
  print "\nUsage"
  print "--preprocess <directory>"
  print "--process <phrase> <directory>\n"
  sys.exit(0);

if len( sys.argv ) < 3:
  printHelp();

if sys.argv[1] == "--preprocess":
  root = sys.argv[2] + 'source/'
  dirs = os.listdir( root );
  print dirs
  

elif sys.argv[2] == "--process":
  pass
else:
  printHelp()
