#!/usr/bin/env python2

import sys, os
import scipy.fftpack, scipy.io.wavfile, scipy.signal
import numpy
import matplotlib.pyplot as plt

def printHelp():
  print "\nUsage"
  print "--preprocess <directory>"
  print "--process <phrase> <directory>\n"
  sys.exit(0);

def ensureDir( f ):
    d = os.getcwd() + '/' + f
    if not os.path.exists(d):
        os.makedirs(d)

if len( sys.argv ) < 3:
  printHelp();

if sys.argv[1] == "--preprocess":
  root = sys.argv[2] + 'source/'
  dirs = os.listdir( root );
  # ffmpeg -y -i source/maryland.webm -ss 180 -t 60 -c:v libvpx-vp9 -pix_fmt yuv420p combined.webm
  # ffmpeg -i combined.webm -acodec pcm_s16le combined.wav
  # sox combined.wav -r 16000 combined2.wav
  # sox combined2.wav combined.wav remix 1,2
  print dirs
elif sys.argv[1] == "--process":

  # load normalized audio file
  vidDir = os.getcwd() + '/' + sys.argv[2] + '/'

  combinedAudio = scipy.io.wavfile.read( vidDir + 'combined.wav' );
  transformAmount = 1024
  end = transformAmount;
  averages = []
  startTimes = []
  lengthTimes = []
  while(end < len(combinedAudio[1])):
    freqs = scipy.fftpack.fft(combinedAudio[1][end-transformAmount:end], transformAmount)
    avg = 0
    for x in xrange(0, transformAmount / 2):
      avg += x * abs(freqs[x])
    averages.append(avg)
    end += 32

  peaks = scipy.signal.find_peaks_cwt(averages, numpy.arange(8000,12000, 4000))
  print peaks
  for peak in peaks:
    startTimes.append(peak * 32 / 16000.0)
    lengthTimes.append(0.5)
  plt.plot(averages)
  plt.show()

  combinedVideo = vidDir + 'combined.webm'
  tmpDir = vidDir + 'tmp/'
  ensureDir( tmpDir )
  inputFile = open( tmpDir + "input.txt", "w" )
  for x in xrange(0, len(startTimes)):
    inputFile.write( "file '" + str(x) + ".webm'\n" )
    os.system( 'ffmpeg -y -i ' + combinedVideo + ' -ss ' + str(startTimes[x]) + ' -t ' + str(lengthTimes[x]) + ' -pix_fmt yuv420p ' + tmpDir + str(x) + '.webm' )
  inputFile.close()

  print startTimes
  print lengthTimes

  os.system( 'ffmpeg -y -f concat -i ' + tmpDir + 'input.txt -c copy ' + vidDir + 'out.webm' )

else:
  printHelp()