#!/usr/bin/env python2

import sys, os

def printHelp():
  print "\nUsage"
  print "--preprocess <directory>"
  print "--process <phrase> <directory>\n"
  sys.exit(0);

def ensureDir( f ):
    d = os.getcwd() + '/' + f
    if not os.path.exists(d):
        os.makedirs(d)

if len( sys.argv ) < 3:
  printHelp();

if sys.argv[1] == "--preprocess":
  root = sys.argv[2] + 'source/'
  dirs = os.listdir( root );
  print dirs
elif sys.argv[1] == "--process":
  if( len( sys.argv ) < 4 ):
    printHelp()
  ensureDir( 'words' )
  words = sys.argv[2].split(" ")
  wordCount = {}
  for word in words:
    if word in wordCount:
      wordCount[ word ] += 1
    else:
      wordCount[ word ] = 1
  print wordCount
else:
  printHelp()